// DO NOT EDIT. generated by webtyp.com/ormc

package chatroom

import (
	"webtyp.com/model"
	"webtyp.com/orm"
)

type Room struct {
	Id        string
	TenantId  string
	Kind      string
	Name      string
	DirectKey string
	CreatedAt int64
	UpdatedAt int64
}

func (m *Room) ModelName() string { return "chat_room" }

func (m *Room) Schema() []model.Field { return RoomModel.Fields }

func (m *Room) Pointers() []any {
	return []any{&m.Id, &m.TenantId, &m.Kind, &m.Name, &m.DirectKey, &m.CreatedAt, &m.UpdatedAt}
}

func (m *Room) IsNil() bool { return m == nil }

func (m *Room) EncodeFields(w model.FieldWriter) {
	if m.Id != "" {
		w.String("id", m.Id)
	}
	w.String("tenant_id", m.TenantId)
	w.String("kind", m.Kind)
	if m.Name != "" {
		w.String("name", m.Name)
	}
	if m.DirectKey != "" {
		w.String("direct_key", m.DirectKey)
	}
	w.Int("created_at", m.CreatedAt)
	if m.UpdatedAt != 0 {
		w.Int("updated_at", m.UpdatedAt)
	}
}

func (m *Room) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok {
		m.Id = v
	}
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
	if v, ok := r.String("kind"); ok {
		m.Kind = v
	}
	if v, ok := r.String("name"); ok {
		m.Name = v
	}
	if v, ok := r.String("direct_key"); ok {
		m.DirectKey = v
	}
	if v, ok := r.Int("created_at"); ok {
		m.CreatedAt = v
	}
	if v, ok := r.Int("updated_at"); ok {
		m.UpdatedAt = v
	}
}

type RoomList []*Room

func (s *RoomList) Len() int                         { return len(*s) }
func (s *RoomList) At(i int) model.Fielder           { return (*s)[i] }
func (s *RoomList) Append() model.Fielder            { v := &Room{}; *s = append(*s, v); return v }
func (s *RoomList) IsNil() bool                      { return s == nil }
func (s *RoomList) EncodeFields(_ model.FieldWriter) {}
func (s *RoomList) DecodeFields(_ model.FieldReader) {}

func (m *Room) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Room_ = struct {
	Id        string
	TenantId  string
	Kind      string
	Name      string
	DirectKey string
	CreatedAt string
	UpdatedAt string
}{
	Id:        "id",
	TenantId:  "tenant_id",
	Kind:      "kind",
	Name:      "name",
	DirectKey: "direct_key",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

func ReadOneRoom(qb *orm.QB, model *Room) (*Room, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllRoom(qb *orm.QB) (RoomList, error) {
	var results RoomList
	err := qb.ReadAll(
		func() model.Model { return &Room{} },
		func(m model.Model) { results = append(results, m.(*Room)) },
	)
	return results, err
}

type Member struct {
	TenantId   string
	RoomId     string
	UserId     string
	LastReadAt int64
}

func (m *Member) ModelName() string { return "chat_member" }

func (m *Member) Schema() []model.Field { return MemberModel.Fields }

func (m *Member) Pointers() []any { return []any{&m.TenantId, &m.RoomId, &m.UserId, &m.LastReadAt} }

func (m *Member) IsNil() bool { return m == nil }

func (m *Member) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("room_id", m.RoomId)
	w.String("user_id", m.UserId)
	w.Int("last_read_at", m.LastReadAt)
}

func (m *Member) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
	if v, ok := r.String("room_id"); ok {
		m.RoomId = v
	}
	if v, ok := r.String("user_id"); ok {
		m.UserId = v
	}
	if v, ok := r.Int("last_read_at"); ok {
		m.LastReadAt = v
	}
}

type MemberList []*Member

func (s *MemberList) Len() int                         { return len(*s) }
func (s *MemberList) At(i int) model.Fielder           { return (*s)[i] }
func (s *MemberList) Append() model.Fielder            { v := &Member{}; *s = append(*s, v); return v }
func (s *MemberList) IsNil() bool                      { return s == nil }
func (s *MemberList) EncodeFields(_ model.FieldWriter) {}
func (s *MemberList) DecodeFields(_ model.FieldReader) {}

func (m *Member) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Member_ = struct {
	TenantId   string
	RoomId     string
	UserId     string
	LastReadAt string
}{
	TenantId:   "tenant_id",
	RoomId:     "room_id",
	UserId:     "user_id",
	LastReadAt: "last_read_at",
}

func ReadOneMember(qb *orm.QB, model *Member) (*Member, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllMember(qb *orm.QB) (MemberList, error) {
	var results MemberList
	err := qb.ReadAll(
		func() model.Model { return &Member{} },
		func(m model.Model) { results = append(results, m.(*Member)) },
	)
	return results, err
}

func (m *Member) SchemaExt() []model.FieldExt {
	return []model.FieldExt{
		{Field: MemberModel.Fields[1], Ref: "room", RefColumn: "id", OnDelete: ""},
	}
}

type Message struct {
	Id          string
	TenantId    string
	RoomId      string
	SenderId    string
	SenderLabel string
	Body        string
	CreatedAt   int64
}

func (m *Message) ModelName() string { return "chat_message" }

func (m *Message) Schema() []model.Field { return MessageModel.Fields }

func (m *Message) Pointers() []any {
	return []any{&m.Id, &m.TenantId, &m.RoomId, &m.SenderId, &m.SenderLabel, &m.Body, &m.CreatedAt}
}

func (m *Message) IsNil() bool { return m == nil }

func (m *Message) EncodeFields(w model.FieldWriter) {
	if m.Id != "" {
		w.String("id", m.Id)
	}
	w.String("tenant_id", m.TenantId)
	w.String("room_id", m.RoomId)
	w.String("sender_id", m.SenderId)
	w.String("sender_label", m.SenderLabel)
	w.String("body", m.Body)
	w.Int("created_at", m.CreatedAt)
}

func (m *Message) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok {
		m.Id = v
	}
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
	if v, ok := r.String("room_id"); ok {
		m.RoomId = v
	}
	if v, ok := r.String("sender_id"); ok {
		m.SenderId = v
	}
	if v, ok := r.String("sender_label"); ok {
		m.SenderLabel = v
	}
	if v, ok := r.String("body"); ok {
		m.Body = v
	}
	if v, ok := r.Int("created_at"); ok {
		m.CreatedAt = v
	}
}

type MessageList []*Message

func (s *MessageList) Len() int                         { return len(*s) }
func (s *MessageList) At(i int) model.Fielder           { return (*s)[i] }
func (s *MessageList) Append() model.Fielder            { v := &Message{}; *s = append(*s, v); return v }
func (s *MessageList) IsNil() bool                      { return s == nil }
func (s *MessageList) EncodeFields(_ model.FieldWriter) {}
func (s *MessageList) DecodeFields(_ model.FieldReader) {}

func (m *Message) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Message_ = struct {
	Id          string
	TenantId    string
	RoomId      string
	SenderId    string
	SenderLabel string
	Body        string
	CreatedAt   string
}{
	Id:          "id",
	TenantId:    "tenant_id",
	RoomId:      "room_id",
	SenderId:    "sender_id",
	SenderLabel: "sender_label",
	Body:        "body",
	CreatedAt:   "created_at",
}

func ReadOneMessage(qb *orm.QB, model *Message) (*Message, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllMessage(qb *orm.QB) (MessageList, error) {
	var results MessageList
	err := qb.ReadAll(
		func() model.Model { return &Message{} },
		func(m model.Model) { results = append(results, m.(*Message)) },
	)
	return results, err
}

func (m *Message) SchemaExt() []model.FieldExt {
	return []model.FieldExt{
		{Field: MessageModel.Fields[2], Ref: "room", RefColumn: "id", OnDelete: ""},
	}
}

type Presence struct {
	TenantId string
	UserId   string
	LastSeen int64
}

func (m *Presence) ModelName() string { return "chat_presence" }

func (m *Presence) Schema() []model.Field { return PresenceModel.Fields }

func (m *Presence) Pointers() []any { return []any{&m.TenantId, &m.UserId, &m.LastSeen} }

func (m *Presence) IsNil() bool { return m == nil }

func (m *Presence) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("user_id", m.UserId)
	w.Int("last_seen", m.LastSeen)
}

func (m *Presence) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
	if v, ok := r.String("user_id"); ok {
		m.UserId = v
	}
	if v, ok := r.Int("last_seen"); ok {
		m.LastSeen = v
	}
}

type PresenceList []*Presence

func (s *PresenceList) Len() int                         { return len(*s) }
func (s *PresenceList) At(i int) model.Fielder           { return (*s)[i] }
func (s *PresenceList) Append() model.Fielder            { v := &Presence{}; *s = append(*s, v); return v }
func (s *PresenceList) IsNil() bool                      { return s == nil }
func (s *PresenceList) EncodeFields(_ model.FieldWriter) {}
func (s *PresenceList) DecodeFields(_ model.FieldReader) {}

func (m *Presence) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Presence_ = struct {
	TenantId string
	UserId   string
	LastSeen string
}{
	TenantId: "tenant_id",
	UserId:   "user_id",
	LastSeen: "last_seen",
}

func ReadOnePresence(qb *orm.QB, model *Presence) (*Presence, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllPresence(qb *orm.QB) (PresenceList, error) {
	var results PresenceList
	err := qb.ReadAll(
		func() model.Model { return &Presence{} },
		func(m model.Model) { results = append(results, m.(*Presence)) },
	)
	return results, err
}

type IdRef struct {
	Id string
}

func (m *IdRef) ModelName() string { return "id_ref" }

func (m *IdRef) Schema() []model.Field { return IdRefModel.Fields }

func (m *IdRef) Pointers() []any { return []any{&m.Id} }

func (m *IdRef) IsNil() bool { return m == nil }

func (m *IdRef) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
}

func (m *IdRef) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok {
		m.Id = v
	}
}

type IdRefList []*IdRef

func (s *IdRefList) Len() int                         { return len(*s) }
func (s *IdRefList) At(i int) model.Fielder           { return (*s)[i] }
func (s *IdRefList) Append() model.Fielder            { v := &IdRef{}; *s = append(*s, v); return v }
func (s *IdRefList) IsNil() bool                      { return s == nil }
func (s *IdRefList) EncodeFields(_ model.FieldWriter) {}
func (s *IdRefList) DecodeFields(_ model.FieldReader) {}

func (m *IdRef) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type OpenDirectArgs struct {
	TenantId    string
	OtherUserId string
}

func (m *OpenDirectArgs) ModelName() string { return "open_direct_args" }

func (m *OpenDirectArgs) Schema() []model.Field { return OpenDirectArgsModel.Fields }

func (m *OpenDirectArgs) Pointers() []any { return []any{&m.TenantId, &m.OtherUserId} }

func (m *OpenDirectArgs) IsNil() bool { return m == nil }

func (m *OpenDirectArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("other_user_id", m.OtherUserId)
}

func (m *OpenDirectArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
	if v, ok := r.String("other_user_id"); ok {
		m.OtherUserId = v
	}
}

type OpenDirectArgsList []*OpenDirectArgs

func (s *OpenDirectArgsList) Len() int               { return len(*s) }
func (s *OpenDirectArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *OpenDirectArgsList) Append() model.Fielder {
	v := &OpenDirectArgs{}
	*s = append(*s, v)
	return v
}
func (s *OpenDirectArgsList) IsNil() bool                      { return s == nil }
func (s *OpenDirectArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *OpenDirectArgsList) DecodeFields(_ model.FieldReader) {}

func (m *OpenDirectArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListRoomsArgs struct {
	TenantId string
}

func (m *ListRoomsArgs) ModelName() string { return "list_rooms_args" }

func (m *ListRoomsArgs) Schema() []model.Field { return ListRoomsArgsModel.Fields }

func (m *ListRoomsArgs) Pointers() []any { return []any{&m.TenantId} }

func (m *ListRoomsArgs) IsNil() bool { return m == nil }

func (m *ListRoomsArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
}

func (m *ListRoomsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
}

type ListRoomsArgsList []*ListRoomsArgs

func (s *ListRoomsArgsList) Len() int               { return len(*s) }
func (s *ListRoomsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListRoomsArgsList) Append() model.Fielder {
	v := &ListRoomsArgs{}
	*s = append(*s, v)
	return v
}
func (s *ListRoomsArgsList) IsNil() bool                      { return s == nil }
func (s *ListRoomsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListRoomsArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListRoomsArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListMessagesArgs struct {
	TenantId string
	RoomId   string
	AfterId  string
	Limit    int64
}

func (m *ListMessagesArgs) ModelName() string { return "list_messages_args" }

func (m *ListMessagesArgs) Schema() []model.Field { return ListMessagesArgsModel.Fields }

func (m *ListMessagesArgs) Pointers() []any {
	return []any{&m.TenantId, &m.RoomId, &m.AfterId, &m.Limit}
}

func (m *ListMessagesArgs) IsNil() bool { return m == nil }

func (m *ListMessagesArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("room_id", m.RoomId)
	w.String("after_id", m.AfterId)
	w.Int("limit", m.Limit)
}

func (m *ListMessagesArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
	if v, ok := r.String("room_id"); ok {
		m.RoomId = v
	}
	if v, ok := r.String("after_id"); ok {
		m.AfterId = v
	}
	if v, ok := r.Int("limit"); ok {
		m.Limit = v
	}
}

type ListMessagesArgsList []*ListMessagesArgs

func (s *ListMessagesArgsList) Len() int               { return len(*s) }
func (s *ListMessagesArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListMessagesArgsList) Append() model.Fielder {
	v := &ListMessagesArgs{}
	*s = append(*s, v)
	return v
}
func (s *ListMessagesArgsList) IsNil() bool                      { return s == nil }
func (s *ListMessagesArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListMessagesArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListMessagesArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type SendMessageArgs struct {
	TenantId string
	RoomId   string
	Body     string
}

func (m *SendMessageArgs) ModelName() string { return "send_message_args" }

func (m *SendMessageArgs) Schema() []model.Field { return SendMessageArgsModel.Fields }

func (m *SendMessageArgs) Pointers() []any { return []any{&m.TenantId, &m.RoomId, &m.Body} }

func (m *SendMessageArgs) IsNil() bool { return m == nil }

func (m *SendMessageArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("room_id", m.RoomId)
	w.String("body", m.Body)
}

func (m *SendMessageArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
	if v, ok := r.String("room_id"); ok {
		m.RoomId = v
	}
	if v, ok := r.String("body"); ok {
		m.Body = v
	}
}

type SendMessageArgsList []*SendMessageArgs

func (s *SendMessageArgsList) Len() int               { return len(*s) }
func (s *SendMessageArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *SendMessageArgsList) Append() model.Fielder {
	v := &SendMessageArgs{}
	*s = append(*s, v)
	return v
}
func (s *SendMessageArgsList) IsNil() bool                      { return s == nil }
func (s *SendMessageArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *SendMessageArgsList) DecodeFields(_ model.FieldReader) {}

func (m *SendMessageArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type MarkReadArgs struct {
	TenantId string
	RoomId   string
}

func (m *MarkReadArgs) ModelName() string { return "mark_read_args" }

func (m *MarkReadArgs) Schema() []model.Field { return MarkReadArgsModel.Fields }

func (m *MarkReadArgs) Pointers() []any { return []any{&m.TenantId, &m.RoomId} }

func (m *MarkReadArgs) IsNil() bool { return m == nil }

func (m *MarkReadArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("room_id", m.RoomId)
}

func (m *MarkReadArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
	if v, ok := r.String("room_id"); ok {
		m.RoomId = v
	}
}

type MarkReadArgsList []*MarkReadArgs

func (s *MarkReadArgsList) Len() int                         { return len(*s) }
func (s *MarkReadArgsList) At(i int) model.Fielder           { return (*s)[i] }
func (s *MarkReadArgsList) Append() model.Fielder            { v := &MarkReadArgs{}; *s = append(*s, v); return v }
func (s *MarkReadArgsList) IsNil() bool                      { return s == nil }
func (s *MarkReadArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *MarkReadArgsList) DecodeFields(_ model.FieldReader) {}

func (m *MarkReadArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type HeartbeatArgs struct {
	TenantId string
}

func (m *HeartbeatArgs) ModelName() string { return "heartbeat_args" }

func (m *HeartbeatArgs) Schema() []model.Field { return HeartbeatArgsModel.Fields }

func (m *HeartbeatArgs) Pointers() []any { return []any{&m.TenantId} }

func (m *HeartbeatArgs) IsNil() bool { return m == nil }

func (m *HeartbeatArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
}

func (m *HeartbeatArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
}

type HeartbeatArgsList []*HeartbeatArgs

func (s *HeartbeatArgsList) Len() int               { return len(*s) }
func (s *HeartbeatArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *HeartbeatArgsList) Append() model.Fielder {
	v := &HeartbeatArgs{}
	*s = append(*s, v)
	return v
}
func (s *HeartbeatArgsList) IsNil() bool                      { return s == nil }
func (s *HeartbeatArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *HeartbeatArgsList) DecodeFields(_ model.FieldReader) {}

func (m *HeartbeatArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListGroupsArgs struct {
	TenantId string
}

func (m *ListGroupsArgs) ModelName() string { return "list_groups_args" }

func (m *ListGroupsArgs) Schema() []model.Field { return ListGroupsArgsModel.Fields }

func (m *ListGroupsArgs) Pointers() []any { return []any{&m.TenantId} }

func (m *ListGroupsArgs) IsNil() bool { return m == nil }

func (m *ListGroupsArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
}

func (m *ListGroupsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
}

type ListGroupsArgsList []*ListGroupsArgs

func (s *ListGroupsArgsList) Len() int               { return len(*s) }
func (s *ListGroupsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListGroupsArgsList) Append() model.Fielder {
	v := &ListGroupsArgs{}
	*s = append(*s, v)
	return v
}
func (s *ListGroupsArgsList) IsNil() bool                      { return s == nil }
func (s *ListGroupsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListGroupsArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListGroupsArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type SaveGroupArgs struct {
	TenantId string
	Id       string
	Name     string
}

func (m *SaveGroupArgs) ModelName() string { return "save_group_args" }

func (m *SaveGroupArgs) Schema() []model.Field { return SaveGroupArgsModel.Fields }

func (m *SaveGroupArgs) Pointers() []any { return []any{&m.TenantId, &m.Id, &m.Name} }

func (m *SaveGroupArgs) IsNil() bool { return m == nil }

func (m *SaveGroupArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
	w.String("name", m.Name)
}

func (m *SaveGroupArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
	if v, ok := r.String("id"); ok {
		m.Id = v
	}
	if v, ok := r.String("name"); ok {
		m.Name = v
	}
}

type SaveGroupArgsList []*SaveGroupArgs

func (s *SaveGroupArgsList) Len() int               { return len(*s) }
func (s *SaveGroupArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *SaveGroupArgsList) Append() model.Fielder {
	v := &SaveGroupArgs{}
	*s = append(*s, v)
	return v
}
func (s *SaveGroupArgsList) IsNil() bool                      { return s == nil }
func (s *SaveGroupArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *SaveGroupArgsList) DecodeFields(_ model.FieldReader) {}

func (m *SaveGroupArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type SetGroupMembersArgs struct {
	TenantId string
	RoomId   string
	UserIds  []IdRef
}

func (m *SetGroupMembersArgs) ModelName() string { return "set_group_members_args" }

func (m *SetGroupMembersArgs) Schema() []model.Field { return SetGroupMembersArgsModel.Fields }

func (m *SetGroupMembersArgs) Pointers() []any { return []any{&m.TenantId, &m.RoomId, &m.UserIds} }

func (m *SetGroupMembersArgs) IsNil() bool { return m == nil }

func (m *SetGroupMembersArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("room_id", m.RoomId)
	{
		arr := w.Array("user_ids", len(m.UserIds))
		for _, x := range m.UserIds {
			arr.Object(&x)
		}
		arr.Close()
	}
}

func (m *SetGroupMembersArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
	if v, ok := r.String("room_id"); ok {
		m.RoomId = v
	}
	if arr, ok := r.Array("user_ids"); ok {
		n := arr.Len()
		m.UserIds = make([]IdRef, n)
		for i := 0; i < n; i++ {
			arr.Object(i, &m.UserIds[i])
		}
	}
}

type SetGroupMembersArgsList []*SetGroupMembersArgs

func (s *SetGroupMembersArgsList) Len() int               { return len(*s) }
func (s *SetGroupMembersArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *SetGroupMembersArgsList) Append() model.Fielder {
	v := &SetGroupMembersArgs{}
	*s = append(*s, v)
	return v
}
func (s *SetGroupMembersArgsList) IsNil() bool                      { return s == nil }
func (s *SetGroupMembersArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *SetGroupMembersArgsList) DecodeFields(_ model.FieldReader) {}

func (m *SetGroupMembersArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListGroupMembersArgs struct {
	TenantId string
	RoomId   string
}

func (m *ListGroupMembersArgs) ModelName() string { return "list_group_members_args" }

func (m *ListGroupMembersArgs) Schema() []model.Field { return ListGroupMembersArgsModel.Fields }

func (m *ListGroupMembersArgs) Pointers() []any { return []any{&m.TenantId, &m.RoomId} }

func (m *ListGroupMembersArgs) IsNil() bool { return m == nil }

func (m *ListGroupMembersArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("room_id", m.RoomId)
}

func (m *ListGroupMembersArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
	if v, ok := r.String("room_id"); ok {
		m.RoomId = v
	}
}

type ListGroupMembersArgsList []*ListGroupMembersArgs

func (s *ListGroupMembersArgsList) Len() int               { return len(*s) }
func (s *ListGroupMembersArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListGroupMembersArgsList) Append() model.Fielder {
	v := &ListGroupMembersArgs{}
	*s = append(*s, v)
	return v
}
func (s *ListGroupMembersArgsList) IsNil() bool                      { return s == nil }
func (s *ListGroupMembersArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListGroupMembersArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListGroupMembersArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type DeleteGroupArgs struct {
	TenantId string
	Id       string
}

func (m *DeleteGroupArgs) ModelName() string { return "delete_group_args" }

func (m *DeleteGroupArgs) Schema() []model.Field { return DeleteGroupArgsModel.Fields }

func (m *DeleteGroupArgs) Pointers() []any { return []any{&m.TenantId, &m.Id} }

func (m *DeleteGroupArgs) IsNil() bool { return m == nil }

func (m *DeleteGroupArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *DeleteGroupArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
	if v, ok := r.String("id"); ok {
		m.Id = v
	}
}

type DeleteGroupArgsList []*DeleteGroupArgs

func (s *DeleteGroupArgsList) Len() int               { return len(*s) }
func (s *DeleteGroupArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *DeleteGroupArgsList) Append() model.Fielder {
	v := &DeleteGroupArgs{}
	*s = append(*s, v)
	return v
}
func (s *DeleteGroupArgsList) IsNil() bool                      { return s == nil }
func (s *DeleteGroupArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *DeleteGroupArgsList) DecodeFields(_ model.FieldReader) {}

func (m *DeleteGroupArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type Participant struct {
	UserId string
	Label  string
	Online bool
}

func (m *Participant) ModelName() string { return "participant" }

func (m *Participant) Schema() []model.Field { return ParticipantModel.Fields }

func (m *Participant) Pointers() []any { return []any{&m.UserId, &m.Label, &m.Online} }

func (m *Participant) IsNil() bool { return m == nil }

func (m *Participant) EncodeFields(w model.FieldWriter) {
	w.String("user_id", m.UserId)
	w.String("label", m.Label)
	w.Bool("online", m.Online)
}

func (m *Participant) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("user_id"); ok {
		m.UserId = v
	}
	if v, ok := r.String("label"); ok {
		m.Label = v
	}
	if v, ok := r.Bool("online"); ok {
		m.Online = v
	}
}

type ParticipantList []*Participant

func (s *ParticipantList) Len() int                         { return len(*s) }
func (s *ParticipantList) At(i int) model.Fielder           { return (*s)[i] }
func (s *ParticipantList) Append() model.Fielder            { v := &Participant{}; *s = append(*s, v); return v }
func (s *ParticipantList) IsNil() bool                      { return s == nil }
func (s *ParticipantList) EncodeFields(_ model.FieldWriter) {}
func (s *ParticipantList) DecodeFields(_ model.FieldReader) {}

func (m *Participant) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type RoomSummary struct {
	RoomId        string
	Kind          string
	Title         string
	Unread        int64
	LastMessageAt int64
	LastPreview   string
}

func (m *RoomSummary) ModelName() string { return "room_summary" }

func (m *RoomSummary) Schema() []model.Field { return RoomSummaryModel.Fields }

func (m *RoomSummary) Pointers() []any {
	return []any{&m.RoomId, &m.Kind, &m.Title, &m.Unread, &m.LastMessageAt, &m.LastPreview}
}

func (m *RoomSummary) IsNil() bool { return m == nil }

func (m *RoomSummary) EncodeFields(w model.FieldWriter) {
	w.String("room_id", m.RoomId)
	w.String("kind", m.Kind)
	w.String("title", m.Title)
	w.Int("unread", m.Unread)
	w.Int("last_message_at", m.LastMessageAt)
	w.String("last_preview", m.LastPreview)
}

func (m *RoomSummary) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("room_id"); ok {
		m.RoomId = v
	}
	if v, ok := r.String("kind"); ok {
		m.Kind = v
	}
	if v, ok := r.String("title"); ok {
		m.Title = v
	}
	if v, ok := r.Int("unread"); ok {
		m.Unread = v
	}
	if v, ok := r.Int("last_message_at"); ok {
		m.LastMessageAt = v
	}
	if v, ok := r.String("last_preview"); ok {
		m.LastPreview = v
	}
}

type RoomSummaryList []*RoomSummary

func (s *RoomSummaryList) Len() int                         { return len(*s) }
func (s *RoomSummaryList) At(i int) model.Fielder           { return (*s)[i] }
func (s *RoomSummaryList) Append() model.Fielder            { v := &RoomSummary{}; *s = append(*s, v); return v }
func (s *RoomSummaryList) IsNil() bool                      { return s == nil }
func (s *RoomSummaryList) EncodeFields(_ model.FieldWriter) {}
func (s *RoomSummaryList) DecodeFields(_ model.FieldReader) {}

func (m *RoomSummary) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type MessageView struct {
	Id          string
	RoomId      string
	SenderId    string
	SenderLabel string
	Body        string
	CreatedAt   int64
	Mine        bool
	Read        bool
}

func (m *MessageView) ModelName() string { return "message_view" }

func (m *MessageView) Schema() []model.Field { return MessageViewModel.Fields }

func (m *MessageView) Pointers() []any {
	return []any{&m.Id, &m.RoomId, &m.SenderId, &m.SenderLabel, &m.Body, &m.CreatedAt, &m.Mine, &m.Read}
}

func (m *MessageView) IsNil() bool { return m == nil }

func (m *MessageView) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("room_id", m.RoomId)
	w.String("sender_id", m.SenderId)
	w.String("sender_label", m.SenderLabel)
	w.String("body", m.Body)
	w.Int("created_at", m.CreatedAt)
	w.Bool("mine", m.Mine)
	w.Bool("read", m.Read)
}

func (m *MessageView) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok {
		m.Id = v
	}
	if v, ok := r.String("room_id"); ok {
		m.RoomId = v
	}
	if v, ok := r.String("sender_id"); ok {
		m.SenderId = v
	}
	if v, ok := r.String("sender_label"); ok {
		m.SenderLabel = v
	}
	if v, ok := r.String("body"); ok {
		m.Body = v
	}
	if v, ok := r.Int("created_at"); ok {
		m.CreatedAt = v
	}
	if v, ok := r.Bool("mine"); ok {
		m.Mine = v
	}
	if v, ok := r.Bool("read"); ok {
		m.Read = v
	}
}

type MessageViewList []*MessageView

func (s *MessageViewList) Len() int                         { return len(*s) }
func (s *MessageViewList) At(i int) model.Fielder           { return (*s)[i] }
func (s *MessageViewList) Append() model.Fielder            { v := &MessageView{}; *s = append(*s, v); return v }
func (s *MessageViewList) IsNil() bool                      { return s == nil }
func (s *MessageViewList) EncodeFields(_ model.FieldWriter) {}
func (s *MessageViewList) DecodeFields(_ model.FieldReader) {}

func (m *MessageView) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type MessageSentEvent struct {
	TenantId  string
	RoomId    string
	MessageId string
	SenderId  string
}

func (m *MessageSentEvent) ModelName() string { return "message_sent_event" }

func (m *MessageSentEvent) Schema() []model.Field { return MessageSentEventModel.Fields }

func (m *MessageSentEvent) Pointers() []any {
	return []any{&m.TenantId, &m.RoomId, &m.MessageId, &m.SenderId}
}

func (m *MessageSentEvent) IsNil() bool { return m == nil }

func (m *MessageSentEvent) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("room_id", m.RoomId)
	w.String("message_id", m.MessageId)
	w.String("sender_id", m.SenderId)
}

func (m *MessageSentEvent) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok {
		m.TenantId = v
	}
	if v, ok := r.String("room_id"); ok {
		m.RoomId = v
	}
	if v, ok := r.String("message_id"); ok {
		m.MessageId = v
	}
	if v, ok := r.String("sender_id"); ok {
		m.SenderId = v
	}
}

type MessageSentEventList []*MessageSentEvent

func (s *MessageSentEventList) Len() int               { return len(*s) }
func (s *MessageSentEventList) At(i int) model.Fielder { return (*s)[i] }
func (s *MessageSentEventList) Append() model.Fielder {
	v := &MessageSentEvent{}
	*s = append(*s, v)
	return v
}
func (s *MessageSentEventList) IsNil() bool                      { return s == nil }
func (s *MessageSentEventList) EncodeFields(_ model.FieldWriter) {}
func (s *MessageSentEventList) DecodeFields(_ model.FieldReader) {}

func (m *MessageSentEvent) Validate(action byte) error {
	return model.ValidateFields(action, m)
}
